In [2]:
import numpy as np
import pandas as pd
import plotly.express as px
from plotly.subplots import make_subplots
import pandapower as pp

# Import data from pickle

In [3]:
# import pickle file
net_Trey_pickle = pp.from_pickle("trey_net_student.p")

In [3]:
# print buses
net_Trey_pickle.bus

            name   type   zone  in_service  geo
0     STMT003438     PQ  Trafo        True  NaN
1     CDBT004764     PQ  North        True  NaN
2     CDBT003746     PQ  North        True  NaN
3     CDBT004760     PQ  North        True  NaN
4     CDBT012139     PQ  North        True  NaN
5     CDBT900784     PQ  North        True  NaN
6     CDBT901452     PQ  South        True  NaN
7     CDBT004774     PQ  South        True  NaN
8     CDBT901604     PQ  South        True  NaN
9     CDBT016055     PQ  South        True  NaN
10            N1     PQ  South        True  NaN
11         60437     PQ  South        True  NaN
12  STMT003438HV  Slack  Trafo        True  NaN

In [4]:
# print load
net_Trey_pickle.load

,name,bus,const_z_p_percent,const_z_q_percent,const_i_p_percent,const_i_q_percent,sn_mva,in_service,type
0,STMT003438,0,0.0,0.0,0.0,0.0,NaN,True,wye
1,CDBT004764,1,0.0,0.0,0.0,0.0,NaN,True,wye
2,CDBT003746,2,0.0,0.0,0.0,0.0,NaN,True,wye
3,CDBT004760,3,0.0,0.0,0.0,0.0,NaN,True,wye
4,CDBT012139,4,0.0,0.0,0.0,0.0,NaN,True,wye
5,CDBT900784,5,0.0,0.0,0.0,0.0,NaN,True,wye
6,CDBT901452,6,0.0,0.0,0.0,0.0,NaN,True,wye
7,CDBT004774,7,0.0,0.0,0.0,0.0,NaN,True,wye
8,CDBT901604,8,0.0,0.0,0.0,0.0,NaN,True,wye
9,CDBT016055,9,0.0,0.0,0.0,0.0,NaN,True,wye
10,N1,10,0.0,0.0,0.0,0.0,NaN,True,wye
11,60437,11,0.0,0.0,0.0,0.0,NaN,True,wye

In [5]:
net_Trey_pickle.ext_grid

,name,vm_pu,va_degree,slack_weight,s_sc_max_mva,s_sc_min_mva,rx_min,rx_max,r0x0_max,x0x_max,in_service
0,ext_grid_0,1.0,0.0,1.0,100.0,None,None,0.1,2.0,2.0,True

In [6]:
net_Trey_pickle.line

,name,from_bus,to_bus,g_us_per_km,df,std_type,in_service,geo
0,GKN3x150_150,0,1,0.0,1.0,None,True,NaN
1,GKN3x150_150_2,1,2,0.0,1.0,None,True,NaN
2,GKN3X95_95,1,3,0.0,1.0,None,True,NaN
3,GKT3X50_50,3,4,0.0,1.0,None,True,NaN
4,GKT3X50_50_2,4,5,0.0,1.0,None,True,NaN
5,GKN3x150_150_3,0,6,0.0,1.0,None,True,NaN
6,GKN3X95_95_2,6,7,0.0,1.0,None,True,NaN
7,GKN3x150_150_4,7,8,0.0,1.0,None,True,NaN
8,GKN3X50_50,7,9,0.0,1.0,None,True,NaN
9,GKN3X50_50_2,6,10,0.0,1.0,None,True,NaN
10,GKN3X240_240,0,11,0.0,1.0,None,True,NaN

In [ ]:
pd.set_option('display.max_columns', None)
net_Trey_pickle.trafo

,name,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,i0_percent,vector_group,vk0_percent,vkr0_percent,mag0_percent,mag0_rx,si0_hv_partial,shift_degree,tap_side,tap_neutral,tap_min,tap_max,tap_step_percent,tap_step_degree,tap_pos,parallel,std_type,df,in_service,tap_changer_type
0,STMT003438,12,0,0.63,18.3,0.42,4.0,0.42,0.65,1.8,Dyn,3.0,0.75,0.3,1.9,1.9,0.0,lv,0.0,-3.0,3.0,2.0,0.0,-3.0,1,None,1.0,True,Ratio

# Adding missing elements
## Lines

In [4]:
# Distance of lines addition
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3x150_150', 'length_km'] = 0.18
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3x150_150_2', 'length_km'] = 0.1
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3X95_95', 'length_km'] = 0.115
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKT3X50_50', 'length_km'] = 0.08
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKT3X50_50_2', 'length_km'] = 0.09
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3x150_150_3', 'length_km'] = 0.135
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3X95_95_2', 'length_km'] = 0.1
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3x150_150_4', 'length_km'] = 0.205
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3X50_50', 'length_km'] = 0.085
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3X50_50_2', 'length_km'] = 0.255
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'] == 'GKN3X240_240', 'length_km'] = 0.34

# Current capacity of lines addition
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3x150_150', na=False), 'max_i_ka'] = 0.4
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3X95_95', na=False), 'max_i_ka'] = 0.252
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains(r'GKN3X50_50|GKT3X50_50', na=False), 'max_i_ka'] = 0.17
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3X240_240', na=False), 'max_i_ka'] = 0.512


# Capacity of lines update
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3x150_150', na=False), 'c_nf_per_km'] = 0.349e3
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3X95_95', na=False), 'c_nf_per_km'] = 0.338e3
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains(r'GKN3X50_50|GKT3X50_50', na=False), 'c_nf_per_km'] = 0.298e3
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3X240_240', na=False), 'c_nf_per_km']  = 0.346e3

# Resistance of lines addition
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3x150_150', na=False), 'r_ohm_per_km'] = 0.124
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3X95_95', na=False), 'r_ohm_per_km'] = 0.193
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains(r'GKN3X50_50|GKT3X50_50', na=False), 'r_ohm_per_km'] = 0.387
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3X240_240', na=False), 'r_ohm_per_km'] = 0.0754

# Reactance of lines addition
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3x150_150', na=False), 'x_ohm_per_km'] = 0.07
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3X95_95', na=False), 'x_ohm_per_km'] = 0.07
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains(r'GKN3X50_50|GKT3X50_50', na=False), 'x_ohm_per_km'] = 0.07
net_Trey_pickle.line.loc[net_Trey_pickle.line['name'].str.contains('GKN3X240_240', na=False), 'x_ohm_per_km'] = 0.07


net_Trey_pickle.line

,name,from_bus,to_bus,g_us_per_km,df,std_type,in_service,geo,length_km,max_i_ka,c_nf_per_km,r_ohm_per_km,x_ohm_per_km
0,GKN3x150_150,0,1,0.0,1.0,None,True,NaN,0.180,0.400,349.0,0.1240,0.07
1,GKN3x150_150_2,1,2,0.0,1.0,None,True,NaN,0.100,0.400,349.0,0.1240,0.07
2,GKN3X95_95,1,3,0.0,1.0,None,True,NaN,0.115,0.252,338.0,0.1930,0.07
3,GKT3X50_50,3,4,0.0,1.0,None,True,NaN,0.080,0.170,298.0,0.3870,0.07
4,GKT3X50_50_2,4,5,0.0,1.0,None,True,NaN,0.090,0.170,298.0,0.3870,0.07
5,GKN3x150_150_3,0,6,0.0,1.0,None,True,NaN,0.135,0.400,349.0,0.1240,0.07
6,GKN3X95_95_2,6,7,0.0,1.0,None,True,NaN,0.100,0.252,338.0,0.1930,0.07
7,GKN3x150_150_4,7,8,0.0,1.0,None,True,NaN,0.205,0.400,349.0,0.1240,0.07
8,GKN3X50_50,7,9,0.0,1.0,None,True,NaN,0.085,0.170,298.0,0.3870,0.07
9,GKN3X50_50_2,6,10,0.0,1.0,None,True,NaN,0.255,0.170,298.0,0.3870,0.07
10,GKN3X240_240,0,11,0.0,1.0,None,True,NaN,0.340,0.512,346.0,0.0754,0.07

## Loads

In [29]:
# Active power addition for all loads
net_Trey_pickle.load['p_mw'] = 4e-3  # 4 kW per house

# Reactive power addition for all loads (cos phi = 0.95 -> q = p * tan(acos(0.95)) = 1.32 kVar)
net_Trey_pickle.load['q_mvar'] = 1.32e-3

# Constant impedance/current shares for all loads (percent)
net_Trey_pickle.load['const_z_p_percent'] = 20
net_Trey_pickle.load['const_i_p_percent'] = 30
net_Trey_pickle.load['const_z_q_percent'] = 20
net_Trey_pickle.load['const_i_q_percent'] = 30

# Scaling for all loads
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'STMT003438', 'scaling'] = 5 # For 5 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT004764', 'scaling'] = 8 # For 8 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT003746', 'scaling'] = 3 # For 3 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT004760', 'scaling'] = 4 # For 4 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT012139', 'scaling'] = 4 # For 4 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT900784', 'scaling'] = 4 # For 4 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT901452', 'scaling'] = 5 # For 5 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT004774', 'scaling'] = 4 # For 4 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT901604', 'scaling'] = 1 # For 1 house
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'CDBT016055', 'scaling'] = 4 # For 4 houses
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == 'N1', 'scaling'] = 1 # For 1 house
net_Trey_pickle.load.loc[net_Trey_pickle.load['name'] == '60437', 'scaling'] = 1 # For 1 house

net_Trey_pickle.load

,name,bus,const_z_p_percent,const_z_q_percent,const_i_p_percent,const_i_q_percent,sn_mva,in_service,type,p_mw,q_mvar,scaling
0,STMT003438,0,20,20,30,30,NaN,True,wye,0.004,0.00132,5
1,CDBT004764,1,20,20,30,30,NaN,True,wye,0.004,0.00132,8
2,CDBT003746,2,20,20,30,30,NaN,True,wye,0.004,0.00132,3
3,CDBT004760,3,20,20,30,30,NaN,True,wye,0.004,0.00132,4
4,CDBT012139,4,20,20,30,30,NaN,True,wye,0.004,0.00132,4
5,CDBT900784,5,20,20,30,30,NaN,True,wye,0.004,0.00132,4
6,CDBT901452,6,20,20,30,30,NaN,True,wye,0.004,0.00132,5
7,CDBT004774,7,20,20,30,30,NaN,True,wye,0.004,0.00132,4
8,CDBT901604,8,20,20,30,30,NaN,True,wye,0.004,0.00132,1
9,CDBT016055,9,20,20,30,30,NaN,True,wye,0.004,0.00132,4
10,N1,10,20,20,30,30,NaN,True,wye,0.004,0.00132,1
11,60437,11,20,20,30,30,NaN,True,wye,0.004,0.00132,1

# Ext grid

In [ ]:
# Add external grid bus 12 (power entry point)
net_Trey_pickle.ext_grid.loc[net_Trey_pickle.ext_grid['name'] == 'ext_grid_0', 'bus'] = 12

net_Trey_pickle.ext_grid

,name,vm_pu,va_degree,slack_weight,s_sc_max_mva,s_sc_min_mva,rx_min,rx_max,r0x0_max,x0x_max,in_service,bus
0,ext_grid_0,1.0,0.0,1.0,100.0,None,None,0.1,2.0,2.0,True,12

# Bus

In [ ]:
# Adding vn_kv to bus
net_Trey_pickle.bus['vn_kv'] = 0.42
net_Trey_pickle.bus.loc[net_Trey_pickle.bus['name'] == 'STMT003438HV', 'vn_kv'] = 18.3

net_Trey_pickle.bus

            name   type   zone  in_service  geo  vn_kv
0     STMT003438     PQ  Trafo        True  NaN   0.42
1     CDBT004764     PQ  North        True  NaN   0.42
2     CDBT003746     PQ  North        True  NaN   0.42
3     CDBT004760     PQ  North        True  NaN   0.42
4     CDBT012139     PQ  North        True  NaN   0.42
5     CDBT900784     PQ  North        True  NaN   0.42
6     CDBT901452     PQ  South        True  NaN   0.42
7     CDBT004774     PQ  South        True  NaN   0.42
8     CDBT901604     PQ  South        True  NaN   0.42
9     CDBT016055     PQ  South        True  NaN   0.42
10            N1     PQ  South        True  NaN   0.42
11         60437     PQ  South        True  NaN   0.42
12  STMT003438HV  Slack  Trafo        True  NaN  18.30

In [ ]:
import pandapower.plotting as pp_plot

NameError: name 'true' is not defined